export interface Facilities {
  dharamshala_available: boolean;
  bhojanshala_available: boolean;
  parking_available: boolean;
  ac_rooms_available: boolean;
  family_rooms_available: boolean;
  lift_available: boolean;
  wheelchair_accessible: boolean;
  drinking_water_available: boolean;
  online_contact_available: boolean;
}

export interface Temple {
  id: string;
  temple_name: string;
  temple_type: "Digambar" | "Shwetambar" | "Both";
  state: string;
  city: string;
  address: string;
  latitude: number;
  longitude: number;
  phone: string;
  history: string;
  timings: string;
  moolnayak: string;
  trust_name: string;
  image_url: string;
  facilities: Facilities;
}

export interface CommunityUpdate {
  id: string;
  temple_id?: string;
  update_type: "new_temple" | "correction" | "photo_upload";
  details: any;
  contributor_email: string;
  contributor_name: string;
  status: "pending" | "approved" | "rejected";
  admin_feedback?: string;
  created_at: string;
}

// 100% Authentic, Deeply Detailed Jain Temples Catalog (34 Madhya Pradesh Temples listed FIRST)
export const MOCK_TEMPLES: Temple[] = [
  // =======================================================
  // --- MADHYA PRADESH JAIN TEMPLES (34 TEMPLES - FIRST) ---
  // =======================================================
  {
    id: "t-indore-kanch",
    temple_name: "Kanch Mandir (Glass Temple)",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Indore",
    address: "Hukumchand Marg, Itwaria Bazar, Indore, MP 452002",
    latitude: 22.7196,
    longitude: 75.8480,
    phone: "+91 731 245 1201",
    history: "Built by the 'Cotton King' Sir Seth Hukumchand Shresthi in 1903. The temple is entirely paneled with thousands of multicolored glass pieces and mirrors imported from Belgium and Italy, creating a breathtaking reflective interior that illustrates Jain stories and moral concepts.",
    timings: "5:00 AM - 12:00 PM, 4:00 PM - 8:30 PM",
    moolnayak: "Lord Chandraprabhu (8th Tirthankara)",
    trust_name: "Sir Seth Hukumchand Digambar Jain Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Kanch_Mandir%2C_Indore.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-indore-gommatagiri",
    temple_name: "Gommatagiri Tirth",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Indore",
    address: "Gommatagiri Hill, Near Indore Airport, Indore, MP 452005",
    latitude: 22.7383,
    longitude: 75.7958,
    phone: "+91 94250 58742",
    history: "Situated on a scenic hillock, Gommatagiri features a majestic 21-foot monolithic statue of Lord Bahubali, constructed in 1981. It also houses 24 beautiful miniature marble temples dedicated to each of the 24 Jain Tirthankaras, offering serene panoramic views of Indore city.",
    timings: "6:00 AM - 9:00 PM",
    moolnayak: "Lord Bahubali (First Tirthankara's Son)",
    trust_name: "Gommatagiri Digambar Jain Prabandhak Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/22/Gommateshwara_Statue_Shravanabelagola.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-highway-mahavirgiri",
    temple_name: "Mahavirgiri Highway Tirth",
    temple_type: "Both",
    state: "Madhya Pradesh",
    city: "Barwaha",
    address: "Indore-Ujjain Highway, KM 28, Madhya Pradesh",
    latitude: 22.9200,
    longitude: 75.8050,
    phone: "+91 98930 11223",
    history: "A modern highway pilgrimage stop established to provide weary travelers with a serene environment for worship, meditation, and pure vegetarian meals. Rests perfectly mid-way on the highway between the commercial hub Indore and the holy city Ujjain.",
    timings: "5:00 AM - 9:30 PM",
    moolnayak: "Lord Mahavira (24th Tirthankara)",
    trust_name: "Mahavirgiri Highway Jain Welfare Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Ranakpur_Jain_Temple_Interior.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-ujjain-avantika",
    temple_name: "Avantika Parshwanath Tirth",
    temple_type: "Shwetambar",
    state: "Madhya Pradesh",
    city: "Ujjain",
    address: "Jaisinghpura, Shipra River Bank, Ujjain, MP 456006",
    latitude: 23.1760,
    longitude: 75.7860,
    phone: "+91 734 258 0041",
    history: "An ancient, highly revered shrine on the banks of the sacred Shipra River in the historic city of Avantika (Ujjain). The ancient idol of Lord Parshwanath here is believed to possess incredible spiritual energy, helping countless devotees attain peace and clarity.",
    timings: "5:00 AM - 10:00 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Avantika Parshwanath Shwetambar Jain Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Parshvanatha_temple_Khajuraho.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-pushpagiri",
    temple_name: "Pushpagiri Siddha Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Dewas",
    address: "Pushpagiri Hill, Songir, Dewas-Bhopal Highway, MP 455001",
    latitude: 22.9512,
    longitude: 76.3812,
    phone: "+91 7272 268224",
    history: "One of the largest modern Jain pilgrimage complexes in central India, sprawling over a scenic hillock along the commercial Indore-Bhopal Highway. It features a majestic, colossal black granite seated statue of Lord Mahavira, alongside an extensive gurukul, modern hospital, Dharamshalas, and dynamic community boarding setups.",
    timings: "5:30 AM - 9:00 PM",
    moolnayak: "Lord Mahavira (Seated Monolith)",
    trust_name: "Shree Pushpagiri Digambar Jain Prabandh Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Pushpgiri_Jain_Tirth%2C_Sonkatch%2C_Dewas.png",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-maksi-parshwanath",
    temple_name: "Maksi Parshwanath Tirth",
    temple_type: "Both",
    state: "Madhya Pradesh",
    city: "Maksi",
    address: "Maksi Mandir Road, Shajapur District, Madhya Pradesh 465106",
    latitude: 23.2512,
    longitude: 76.1512,
    phone: "+91 7364 252 234",
    history: "A highly revered joint temple visited by millions of both Digambar and Shwetambar devotees, situated mid-way on the Ujjain-Bhopal Highway. It houses an incredibly ancient 1000-year-old black stone idol of Lord Parshwanath, with massive adjoining pilgrim boarding blocks and massive dining halls.",
    timings: "5:00 AM - 9:30 PM",
    moolnayak: "Lord Maksi Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Maksi Parshwanath Digambar-Shwetambar Joint Trust Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Ranakpur_Jain_Temple_Interior.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-amarkantak",
    temple_name: "Amarkantak Sarvodaya Jain Tirth",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Amarkantak",
    address: "Sarvodaya Tirth Campus, Source of Narmada River, Anuppur District, MP 484886",
    latitude: 22.6712,
    longitude: 81.7512,
    phone: "+91 7629 269 110",
    history: "Located at the holy origin of the Narmada River in Amarkantak. This architectural marvel features the world's largest, highly imposing **24-ton octo-alloy (Ashtadhatu) statue** of Lord Adinath, constructed under the spiritual vision of Acharya Vidyasagar Ji. The temple is built entirely of pink sandstone without cement or iron.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Adinath (24-ton Octo-Alloy Monolith)",
    trust_name: "Shree Sarvodaya Digambar Jain Tirth Trust Amarkantak",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Amarkantak_Jain_Temple.png",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-pisanhari",
    temple_name: "Pisanhari Ki Madiya",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Jabalpur",
    address: "Near Netaji Subhash Chandra Bose Medical College, Jabalpur, MP 482003",
    latitude: 23.1362,
    longitude: 79.8823,
    phone: "+91 761 244 0251",
    history: "A famous 500-year-old hilltop temple built by a poor old woman (Pisanhari) who ground wheat ('Pisan') using hand mills to earn money for construction bricks. Rather than offering gold, she offered her hand-operated grinding stones, which are still preserved at the temple entrance.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Adinath (1st Tirthankara)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Pisanhari Ki Madiya Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Pisanhari_ki_Marhia_Jain_Temple%2C_Jabalpur%2C_Madhya_Pradesh%2C_India.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-bajrangarh",
    temple_name: "Bajrangarh Fortress Atishaya Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Guna",
    address: "Bajrangarh Fort Campus, near Guna town, Madhya Pradesh 473001",
    latitude: 24.5812,
    longitude: 77.3012,
    phone: "+91 7542 258 201",
    history: "A spectacular, ancient fortress shrine constructed inside the historical walls of Bajrangarh Fort in 1236 AD. It houses massive, highly imposing 18-foot red-sandstone monolithic standing statues of Lord Shantinath, Lord Kunthunath, and Lord Aranath.",
    timings: "6:00 AM - 8:00 PM",
    moolnayak: "Lord Shantinath (18-foot monolithic statue)",
    trust_name: "Shree Digambar Jain Atishaya Kshetra Bajrangarh Mandir Committee",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Gopachal_Parvat_-_Rockcut_Jain_Sculptures.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-paporaji",
    temple_name: "Paporaji Atishaya Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Tikamgarh",
    address: "Paporaji Hill, near Tikamgarh Town, Madhya Pradesh 472001",
    latitude: 24.7812,
    longitude: 78.8912,
    phone: "+91 7683 242 101",
    history: "An ancient, highly revered pilgrimage hill cluster dating back to the 12th century. It features exactly 108 beautiful white spired temples crawling up the hillside, housing priceless ancient sandstone and marble idols of different Tirthankaras.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Lord Adinath (1st Tirthankara)",
    trust_name: "Shree Digambar Jain Atishaya Kshetra Paporaji Mandir Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-pavagiri-una",
    temple_name: "Pavagiri Siddha Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Una",
    address: "Pavagiri Hill, Una, Khargone District, Madhya Pradesh 451441",
    latitude: 21.8156,
    longitude: 75.4854,
    phone: "+91 7282 262334",
    history: "An ancient, highly sacred salvation site (Siddha Kshetra) where 99 crore saints attained salvation. It contains several spectacular stone carved temples dating back to the Paramara dynasty in the 11th century, overlooking serene valley views.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Lord Shantinath (16th Tirthankara)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Pavagiri Una Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-mandavgarh",
    temple_name: "Mandavgarh Parshwanath Tirth",
    temple_type: "Shwetambar",
    state: "Madhya Pradesh",
    city: "Mandu",
    address: "Mandu Fort City, Dhar District, Madhya Pradesh 454010",
    latitude: 22.3512,
    longitude: 75.4012,
    phone: "+91 7292 263 226",
    history: "Nestled within the scenic, historic fort ruins of Mandavgarh (Mandu). This ancient Paramara-era Shwetambar temple features a majestic white marble idol of Lord Parshwanath, surrounded by spectacular structural gateways and pristine green fort valleys.",
    timings: "6:00 AM - 8:00 PM",
    moolnayak: "Lord Suparshwanath (7th Tirthankara)",
    trust_name: "Shree Mandavgarh Shwetambar Jain Tirth Trust Mandu",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Ranakpur_Jain_Temple_Interior.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-gyaraspur",
    temple_name: "Gyaraspur Maladevi Jain Temple",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Vidisha",
    address: "Gyaraspur Hill Slope, Vidisha District, Madhya Pradesh 464220",
    latitude: 23.8012,
    longitude: 78.1012,
    phone: "+91 7592 245 102",
    history: "A spectacular, ancient 9th-century structural monument (Maladevi Temple) carved directly into the rocky hillside slope of Gyaraspur. Renowned for its classical Indian sandstone pillars, spires, and historical carvings, managed under the Archaeological Survey of India (ASI).",
    timings: "8:00 AM - 6:00 PM",
    moolnayak: "Lord Adinath (1st Tirthankara)",
    trust_name: "Archaeological Survey of India & Sagar Jain Samaj",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Gopachal_Parvat_-_Rockcut_Jain_Sculptures.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-barwaha-chintamani",
    temple_name: "Chintamani Parshwanath Mandir",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Barwaha",
    address: "Main Mandir Road, Barwaha, Khargone District, MP 451115",
    latitude: 22.2512,
    longitude: 76.0412,
    phone: "+91 7280 222 102",
    history: "A historic, highly popular highway temple in the town of Barwaha. It serves as an active transit center for yatris traveling along the Indore-Khargone corridor, providing neat boarding facilities and daily spiritual services.",
    timings: "6:00 AM - 9:00 PM",
    moolnayak: "Lord Chintamani Parshwanath (23rd Tirthankara)",
    trust_name: "Barwaha Digambar Jain Samaj Prabandhak Committee",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Ranakpur_Jain_Temple_Interior.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-sonagiri",
    temple_name: "Sonagiri Siddha Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Datia",
    address: "Sonagiri Hill, Datia District, Madhya Pradesh 475685",
    latitude: 25.7133,
    longitude: 78.4354,
    phone: "+91 7522 262 222",
    history: "A unique spiritual mountain featuring 77 sparkling white spired temples crawling up the green rocky hillside, and 26 additional temples in the village valley. Since the 8th century, it is highly revered as a place of asceticism where 5.5 crore saints (including King Nanganand) attained Moksha.",
    timings: "5:00 AM - 8:30 PM",
    moolnayak: "Lord Chandraprabhu (Temple No. 57, 11-foot monolithic statue)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Sonagiri Prabandhkarini Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-kundalpur-mp",
    temple_name: "Kundalpur Bade Baba Tirth",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Kundalpur",
    address: "Kundalpur Hills, Damoh District, Madhya Pradesh 470771",
    latitude: 24.0456,
    longitude: 79.6456,
    phone: "+91 7811 254 321",
    history: "Famous for the highly imposing, ancient 15-foot red-sandstone monolithic statue of Lord Adinath (popularly worshipped as 'Bade Baba'). A magnificent, world-class new temple has been built around the mountain base recently under the blessings of Acharya Vidyasagar Ji Maharaj.",
    timings: "5:00 AM - 9:00 PM",
    moolnayak: "Lord Adinath / Bade Baba (1st Tirthankara)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Kundalpur Trust Committee",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Temples_kundalpur.JPG",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-bawangaja",
    temple_name: "Bawangaja Adinath Chulagiri",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Barwani",
    address: "Bawangaja Hill Road, Barwani District, Madhya Pradesh 451551",
    latitude: 22.0125,
    longitude: 74.8845,
    phone: "+91 7290 223 102",
    history: "Houses the world's largest monolithic brown-granite statue of Lord Adinath (84 feet tall / 52 'Gaja', hence the name Bawangaja). Carved out of a single volcanic rock face on a mountain ridge in the 12th century, it is a structural wonder surrounded by lush Satpura forests.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Adinath (84-foot Monolith)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Bawangaja Trust Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Bawangajastatue.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-gopachal",
    temple_name: "Gopachal Parvat rock monuments",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Gwalior",
    address: "Gopachal Parvat, Near Gwalior Fort, Gwalior, MP 474001",
    latitude: 26.2166,
    longitude: 78.1692,
    phone: "+91 751 240 9851",
    history: "Gopachal Parvat contains spectacular rock-cut monuments containing gigantic monolithic statues of Jain Tirthankaras carved between 1341 and 1479 AD under Tomar rulers. The largest is a 47-foot seated statue of Lord Adinath, a majestic monument carved directly into the cliff sides.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Adinath (47-foot monolithic statue)",
    trust_name: "Gopachal Parvat Digambar Jain Kshetr Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Gopachal_Parvat_-_Rockcut_Jain_Sculptures.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false
    }
  },
  {
    id: "t-siddhachal",
    temple_name: "Siddhachal Gwalior Caves",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Gwalior Fort",
    address: "Gwalior Fort Urvai Gate, Gwalior, MP 474001",
    latitude: 26.2245,
    longitude: 78.1612,
    phone: "+91 751 242 0151",
    history: "A group of ancient rock-cut cave temples lining the Urvai Gate slopes inside the historic Gwalior Fort. Carved in the 15th century, the monuments include colossal standing and seated monolithic statues, dominated by a massive 58-foot standing statue of Lord Adinath.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Adinath (58-foot standing monolith)",
    trust_name: "Gwalior Fort Digambar Jain Mandir Committee",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Jain_statues_in_Siddhachal_Caves.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-manua-bhan",
    temple_name: "Manua Bhan Tekri Tirth",
    temple_type: "Both",
    state: "Madhya Pradesh",
    city: "Bhopal",
    address: "Lalghati, Airport Road, Bhopal, MP 462030",
    latitude: 23.2845,
    longitude: 77.3685,
    phone: "+91 755 273 4211",
    history: "A widely visited hilltop pilgrimage shrine accessed via a scenic ropeway cable car. It houses the Charan Paduka of Acharya Mantungacharya, author of the famous 'Bhaktamar Stotra'. It offers panoramic vistas of Bhopal's historic lakes and commercial city lines.",
    timings: "6:30 AM - 9:00 PM",
    moolnayak: "Lord Mahavira (24th Tirthankara)",
    trust_name: "Shree Manua Bhan Tekri Prabandhak Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-thubonji",
    temple_name: "Thubonji Siddha Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Chanderi",
    address: "Thubon Village, near Chanderi, Ashoknagar District, MP 473446",
    latitude: 24.7125,
    longitude: 78.1812,
    phone: "+91 7547 253 234",
    history: "A highly tranquil and historic temple cluster comprising 26 beautifully carved sandstone shrines. Devotees visit to seek blessings from 'Adinath Bade Baba', a colossal 12-foot sandstone standing monolith carved during the Pratihara reign.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Lord Adinath (12-foot standing monolith)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Thubonji Prabandhak Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-khajuraho",
    temple_name: "Khajuraho Parsvanath Temple",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Khajuraho",
    address: "Eastern Group of Temples, Khajuraho, Chhatarpur District, MP 471606",
    latitude: 24.8485,
    longitude: 79.9125,
    phone: "+91 7686 274 024",
    history: "A breathtaking UNESCO World Heritage site constructed during the Chandela dynasty in the 10th century. Renowned for its highly sophisticated architectural carvings of celestial dancers, musicians, and deities, reflecting the pinnacle of medieval Indian stone art.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Archaeological Survey of India & Local Jain Samaj Joint Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Parshvanatha_temple_Khajuraho.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-aharji",
    temple_name: "Aharji Atishaya Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Tikamgarh",
    address: "Ahar Village, Tikamgarh District, Madhya Pradesh 472001",
    latitude: 24.7312,
    longitude: 78.8542,
    phone: "+91 7683 245 101",
    history: "A highly historic Chandela-era pilgrimage site famous for its magnificent 18-foot standing monolithic statue of Lord Shantinath. The pink-sandstone colossus is flanked by beautiful carvings of ancient guardian spirits, surrounded by peaceful rural woodlands.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Lord Shantinath (18-foot monolithic statue)",
    trust_name: "Shree Digambar Jain Atishaya Kshetra Aharji Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/29/Aharji.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-nainagiri",
    temple_name: "Nainagiri Siddha Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Sagar",
    address: "Reshandigiri Hills, Sagar District, Madhya Pradesh 470001",
    latitude: 24.2812,
    longitude: 79.2012,
    phone: "+91 7582 284 311",
    history: "Also known as Reshandigiri, this serene sanctuary features a group of 36 gleaming white spired temples surrounding a beautiful, sacred lake. Devotees visit this peaceful valley seeking deep meditation and ascetic retreat, preserving centuries of spiritual silence.",
    timings: "5:00 AM - 8:30 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Nainagiri Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-mangalgiri",
    temple_name: "Mangalgiri Sagar Tirth",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Sagar",
    address: "Mangalgiri Hill, Sagar, MP 470002",
    latitude: 23.8542,
    longitude: 78.7812,
    phone: "+91 7582 225 104",
    history: "A beautiful hilltop spiritual complex designed recently to house a majestic, massive seated statue of Lord Mahavira. It serves as an active educational center and provides spacious rooms and pure meals to highway yatris.",
    timings: "6:00 AM - 9:00 PM",
    moolnayak: "Lord Mahavira (Seated Monolith)",
    trust_name: "Shree Mangalgiri Digambar Jain Prabandhak Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-chanderi-town",
    temple_name: "Chanderi Town Jain Basadis",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Chanderi",
    address: "Main Fort Road, Chanderi, Ashoknagar District, MP 473446",
    latitude: 24.4212,
    longitude: 78.1312,
    phone: "+91 7547 252 110",
    history: "The historic weaving town of Chanderi houses several ancient Jain basadis dating back to the Pratihara and Bundela dynasties. They are renowned for their highly detailed sand carvings and extensive collections of ancient metal and stone icons.",
    timings: "6:00 AM - 8:00 PM",
    moolnayak: "Lord Adinath (1st Tirthankara)",
    trust_name: "Chanderi Digambar Jain Samaj Prabandhak Committee",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Gopachal_Parvat_-_Rockcut_Jain_Sculptures.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-bandhaji",
    temple_name: "Bandhaji Atishaya Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Sagar",
    address: "Bandha Village, Sagar Border, MP 470001",
    latitude: 24.4542,
    longitude: 78.4812,
    phone: "+91 7582 291 002",
    history: "A highly revered miraculous temple housing a historic idol of Lord Ajitnath. Devotees visit seeking relief from domestic, business, and health obstacles, participating in daily peaceful spiritual ceremonies.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Lord Ajitnath (2nd Tirthankara)",
    trust_name: "Shree Digambar Jain Atishaya Kshetra Bandhaji Mandir",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-bhojpur",
    temple_name: "Bhojpur Shantinath Temple",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Bhojpur",
    address: "Near Bhojeshwar Temple, Bhojpur, Raisen District, MP 464993",
    latitude: 23.1012,
    longitude: 77.5812,
    phone: "+91 755 240 1002",
    history: "Located adjacent to the world-famous colossal Bhojeshwar Shiva Temple, this historic Jain shrine features a massive, highly imposing 20-foot monolithic statue of Lord Shantinath, constructed in the 11th century under King Bhoja of the Paramara dynasty.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Shantinath (20-foot monolithic statue)",
    trust_name: "Archaeological Survey of India & Sagar Jain Samaj",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Gopachal_Parvat_-_Rockcut_Jain_Sculptures.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-nemawar",
    temple_name: "Nemawar Siddha Kshetra",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Dewas",
    address: "Narmada River Bank, Nemawar, Dewas District, MP 455339",
    latitude: 22.4812,
    longitude: 76.9812,
    phone: "+91 7273 283 104",
    history: "An ancient, highly revered Siddha Kshetra located directly on the scenic banks of the sacred Narmada River. It is the auspicious place where countless Jain ascetics attained salvation, offering beautiful white sandstone architecture with peaceful river view vistas.",
    timings: "5:00 AM - 9:00 PM",
    moolnayak: "Lord Adinath (1st Tirthankara)",
    trust_name: "Shree Digambar Jain Siddha Kshetra Nemawar Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-makronia",
    temple_name: "Makronia Jain Mandir",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Sagar",
    address: "Makronia Chauraha, Sagar, MP 470004",
    latitude: 23.8712,
    longitude: 78.7912,
    phone: "+91 7582 231 102",
    history: "A highly active commercial and spiritual center in Sagar, providing the local community and highway yatris with a pristine marble temple, peaceful prayer halls, and daily religious lectures.",
    timings: "6:00 AM - 9:00 PM",
    moolnayak: "Lord Chandraprabhu (8th Tirthankara)",
    trust_name: "Makronia Digambar Jain Mandir Welfare Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-nishaiji",
    temple_name: "Nishaiji Sukha Tirth",
    temple_type: "Digambar",
    state: "Madhya Pradesh",
    city: "Sagar",
    address: "Nishaiji Campus, Sukha, Sagar, MP 470001",
    latitude: 23.9012,
    longitude: 78.8212,
    phone: "+91 7582 235 110",
    history: "A highly peaceful pilgrimage center dedicated to the spiritual memory of Acharya Taran Taran Mandala, the founder of the Taran Panth sect. Devotees visit for quiet meditation, scripture reading, and simple spiritual lifestyles.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Jain Holy Scriptures (Granth Ji)",
    trust_name: "Shree Taran Taran Mandala Digambar Jain Trust Sagar",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },

  // =======================================================
  // --- OUT-OF-STATE FAMOUS NATIONAL TEMPLES (NEXT) ---
  // =======================================================
  {
    id: "t-palitana",
    temple_name: "Palitana Shatrunjaya Tirth",
    temple_type: "Shwetambar",
    state: "Gujarat",
    city: "Palitana",
    address: "Shatrunjaya Hills, Palitana, Bhavnagar District, Gujarat 364250",
    latitude: 21.4984,
    longitude: 71.8022,
    phone: "+91 2848 252 001",
    history: "Shatrunjaya is the most sacred pilgrimage place (Maha-tirth) for Shwetambar Jains, boasting over 860 marble-carved temples sprawling across a beautiful mountain ridge. Devotees climb 3,500+ stone steps to reach the main peak, where the primary temple of Lord Adinath sparkles in pristine white marble.",
    timings: "5:30 AM - 7:00 PM (No overnight stay allowed on the hill)",
    moolnayak: "Lord Adinath / Rishabhdev (1st Tirthankara)",
    trust_name: "Seth Anandji Kalyanji Devasthan Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Palitana_Jain_temples.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-shikharji",
    temple_name: "Sammed Shikharji (Parasnath Hill)",
    temple_type: "Both",
    state: "Jharkhand",
    city: "Madhuban",
    address: "Parasnath Hills, Madhuban, Giridih District, Jharkhand 825136",
    latitude: 23.9786,
    longitude: 86.1554,
    phone: "+91 6532 232 235",
    history: "Sammed Shikharji is the crown jewel of Jain pilgrimage sites. Out of the 24 Jain Tirthankaras, exactly 20 attained ultimate salvation (Moksha/Nirvana) on these holy mountain peaks through deep, silent meditation. Pilgrims perform a rigorous 27-kilometer barefoot march (Parikrama) across 31 sacred shrines.",
    timings: "3:30 AM - 6:00 PM (Ascent begins in the dark, overnight stays strictly banned)",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Digambar Jain Madhuban Kothi & Seth Anandji Joint Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Parshvanatha_temple_Khajuraho.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-ranakpur",
    temple_name: "Ranakpur Chaumukha Temple",
    temple_type: "Shwetambar",
    state: "Rajasthan",
    city: "Ranakpur",
    address: "Sadri-Ranakpur Road, Pali District, Rajasthan 306702",
    latitude: 25.1158,
    longitude: 73.4725,
    phone: "+91 2934 285 022",
    history: "Constructed in 1439 AD by Dharna Shah, a wealthy Jain businessman, under the patronage of Rana Kumbha. Recognized globally for its spectacular marble architecture, featuring exactly 1,444 uniquely hand-carved pillars - no two pillars are alike!",
    timings: "12:00 PM - 5:00 PM (Devotees worship early morning)",
    moolnayak: "Lord Adinath / Rishabhdev (1st Tirthankara)",
    trust_name: "Sheth Anandji Kalyanji Devasthan Trust (Ranakpur Division)",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Ranakpur_Jain_Temple_Interior.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-dilwara",
    temple_name: "Dilwara Marble Temples",
    temple_type: "Shwetambar",
    state: "Rajasthan",
    city: "Mount Abu",
    address: "Delwara, Mount Abu, Sirohi District, Rajasthan 307501",
    latitude: 24.6128,
    longitude: 72.7239,
    phone: "+91 2974 238 124",
    history: "A group of five legendary marble temples dating back to the 11th and 13th centuries AD, built by Vimal Shah and Vastupal-Tejpal. Renowned for their intricate ceiling carvings, lace-like marble canopies, and beautiful ornamental pillars.",
    timings: "12:00 PM - 6:00 PM (Devotees/Pooja allowed 6:00 AM - 12:00 PM)",
    moolnayak: "Lord Adinath (Vimal Vasahi Temple)",
    trust_name: "Shree Kalyanji Parmanandji Mount Abu Devsthan Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/3/30/Dilwara_Jain_Temple_ceiling.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-shravanabelagola",
    temple_name: "Shravanabelagola Vindhyagiri",
    temple_type: "Digambar",
    state: "Karnataka",
    city: "Shravanabelagola",
    address: "Vindhyagiri Hills, Shravanabelagola, Hassan District, Karnataka 573135",
    latitude: 12.8596,
    longitude: 76.4862,
    phone: "+91 8176 257 226",
    history: "Home to the world-famous 57-foot monolithic statue of Lord Gommateshwara (Bahubali), carved in 981 AD out of a single block of fine grey granite by Western Ganga Dynasty minister Chavundaraya.",
    timings: "6:00 AM - 6:30 PM",
    moolnayak: "Lord Bahubali (Monolithic Statue)",
    trust_name: "Shree Bahubali Digambar Jain Atishaya Kshetra Mahasamiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/22/Gommateshwara_Statue_Shravanabelagola.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-pavapuri",
    temple_name: "Pavapuri Jal Mandir",
    temple_type: "Shwetambar",
    state: "Bihar",
    city: "Pavapuri",
    address: "Jal Mandir Path, Nalanda District, Bihar 803115",
    latitude: 25.0934,
    longitude: 85.5186,
    phone: "+91 6112 284 221",
    history: "Jal Mandir (Water Temple) stands in the exact center of a vast red-lotus lake where Lord Mahavira, the last Jain Tirthankara, attained Nirvana (salvation) in 527 BC and was cremated. Built of pristine white marble, the temple is connected to the shore by a 600-foot stone bridge.",
    timings: "5:00 AM - 9:00 PM",
    moolnayak: "Lord Mahavira (Charan Paduka)",
    trust_name: "Shree Pavapuri Jain Shwetambar Bihar Prabandhak Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/2/23/Jal_Mandir_Pawapuri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-hastinapur",
    temple_name: "Hastinapur Jambudweep Tirth",
    temple_type: "Digambar",
    state: "Uttar Pradesh",
    city: "Hastinapur",
    address: "Jambudweep Campus, Hastinapur, Meerut District, UP 250404",
    latitude: 29.1684,
    longitude: 78.0204,
    phone: "+91 1233 280 112",
    history: "Designed under the vision of revered Jain nun Gyanmatiji in 1985. Hastinapur is the birthplace of three Tirthankaras (Lord Shantinath, Kunthunath, and Aranath). The campus is unique for containing a massive, mathematically precise 3D model of Jain cosmology ('Jambudweep').",
    timings: "5:30 AM - 9:00 PM",
    moolnayak: "Lord Shantinath (16th Tirthankara)",
    trust_name: "Digambar Jain Trilok Sansthan Jambudweep Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Sonagiri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-delhi-lalmandir",
    temple_name: "Sri Digambar Jain Lal Mandir",
    temple_type: "Digambar",
    state: "Delhi",
    city: "Old Delhi",
    address: "Netaji Subhash Marg, Opposite Red Fort, Chandni Chowk, Delhi 110006",
    latitude: 28.6562,
    longitude: 77.2369,
    phone: "+91 11 2328 0945",
    history: "The oldest and best-known Jain temple in Delhi, originally built in 1656 out of red sandstone during the Mughal Emperor Shah Jahan's reign. Located directly opposite the majestic Red Fort, it also houses the famous 'Jain Charity Birds Hospital'.",
    timings: "5:30 AM - 11:30 AM, 6:00 PM - 9:30 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Prabandhak Commitee Sri Digambar Jain Lal Mandir Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Shri_Digambar_Jain_Lal_Mandir%2C_Delhi.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: false,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-nakoda",
    temple_name: "Nakoda Parshwanath Tirth",
    temple_type: "Shwetambar",
    state: "Rajasthan",
    city: "Nakoda",
    address: "Nakoda Road, Mewanagar, Barmer District, Rajasthan 344033",
    latitude: 25.8078,
    longitude: 72.2458,
    phone: "+91 2928 283 234",
    history: "A highly miraculous and universally visited multi-religious spiritual hub in the Rajasthan desert. The idol of Nakoda Bhairavdev (guardian deity) was installed in 1438 AD and attracts millions of pilgrims of all faiths.",
    timings: "5:00 AM - 10:00 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Nakoda Parshwanath Jain Shwetambar Tirth Trust",
    image_url: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-babu-amishchand",
    temple_name: "Babu Amichand Adishwarji Temple",
    temple_type: "Shwetambar",
    state: "Maharashtra",
    city: "Mumbai",
    address: "Ridge Road, Walkeshwar, Malabar Hill, Mumbai, MH 400006",
    latitude: 18.9554,
    longitude: 72.8028,
    phone: "+91 22 2369 2201",
    history: "Constructed in 1904, this ornate temple on prestigious Malabar Hill is famous for its marble carvings, custom painted dome frescoes illustrating the Zodiac signs and Tirthankaras, and serene garden compound.",
    timings: "6:00 AM - 9:00 PM",
    moolnayak: "Lord Adinath / Adishwar (1st Tirthankara)",
    trust_name: "Babu Amichand Panalal Adishwarji Jain Temple Trust",
    image_url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: false,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-lodhruva",
    temple_name: "Lodhruva Parshwanath Temple",
    temple_type: "Shwetambar",
    state: "Rajasthan",
    city: "Jaisalmer",
    address: "Lodhruva Sand Dunes, Jaisalmer District, Rajasthan 345001",
    latitude: 26.9612,
    longitude: 70.8125,
    phone: "+91 2992 250 115",
    history: "A structural sand masterpiece built in yellow sandstone, featuring a legendary copper Kalpavriksha tree model and intricate geometric stone screen carvings in the Jaisalmer desert.",
    timings: "6:00 AM - 7:30 PM",
    moolnayak: "Lord Lodhruva Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Lodhruva Parshwanath Shwetambar Jain Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-kolanpak",
    temple_name: "Kolanpak Jain Temple",
    temple_type: "Shwetambar",
    state: "Telangana",
    city: "Kolanupaka",
    address: "Kolanupaka Village, Alair Mandhal, Yadadri Bhuvanagiri, Telangana 508101",
    latitude: 17.7125,
    longitude: 79.0456,
    phone: "+91 8685 281 224",
    history: "A highly prominent 2,000-year-old temple complex constructed in red sandstone, housing a famous, colossal 5-foot green jade/emerald Tirthankara idol.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Rishabhdev (Emerald statue)",
    trust_name: "Shree Kolanupaka Shwetambar Jain Mandir Trust",
    image_url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-kesariyaji-raj",
    temple_name: "Kesariyaji Rishabhdeo Tirth",
    temple_type: "Both",
    state: "Rajasthan",
    city: "Rishabhdeo",
    address: "Udaipur-Ahmedabad Highway, Udaipur District, Rajasthan 313801",
    latitude: 24.0845,
    longitude: 73.6845,
    phone: "+91 2907 232 234",
    history: "Ancient black stone temple. Worshippers offer massive quantities of pure saffron paste daily in deep prayers. Visited extensively by all traditions and local tribes.",
    timings: "5:00 AM - 9:00 PM",
    moolnayak: "Lord Rishabhdev / Adinath (1st Tirthankara)",
    trust_name: "Shree Kesariyaji Jain Mandir Devsthan Committee",
    image_url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-padampura-raj",
    temple_name: "Bara Padampura Atishaya Kshetra",
    temple_type: "Digambar",
    state: "Rajasthan",
    city: "Padampura",
    address: "Shivdaspura-Padampura Road, Jaipur, Rajasthan 303903",
    latitude: 26.6845,
    longitude: 75.8912,
    phone: "+91 141 297 1222",
    history: "A famous miracle temple established in 1944. An elegant white marble idol of Lord Padmaprabhu was discovered while digging sand.",
    timings: "5:30 AM - 9:00 PM",
    moolnayak: "Lord Padmaprabhu (6th Tirthankara)",
    trust_name: "Shree Digambar Jain Atishaya Kshetra Mandir Padampura",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-melsithamur",
    temple_name: "Mel Sithamur Jain Math",
    temple_type: "Digambar",
    state: "Tamil Nadu",
    city: "Mel Sithamur",
    address: "Gingee-Tindivanam Road, Villupuram District, Tamil Nadu 604206",
    latitude: 12.2542,
    longitude: 79.4212,
    phone: "+91 4145 234 211",
    history: "The ancient spiritual math of Tamil Jains, featuring beautiful rock-cut caverns and an active community education center preserving old scripts.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Neminath (22nd Tirthankara)",
    trust_name: "Mel Sithamur Digambar Jain Math Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-varanga",
    temple_name: "Varanga Kere Floating Temple",
    temple_type: "Digambar",
    state: "Karnataka",
    city: "Varanga",
    address: "Kere Basadi Lake, Varanga, Udupi District, Karnataka 576112",
    latitude: 13.4125,
    longitude: 75.0125,
    phone: "+91 820 258 4211",
    history: "A unique, floating lake temple. Pilgrims take a wooden rowboat across green waters to reach this serene spired shrine in Karnataka.",
    timings: "7:00 AM - 6:00 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Varanga Kere Basadi Temple Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-kundadri",
    temple_name: "Kundadri Hill Cave Temple",
    temple_type: "Digambar",
    state: "Karnataka",
    city: "Tirthahalli",
    address: "Kundadri Hill Peak, Shimoga District, Karnataka 577432",
    latitude: 13.5512,
    longitude: 75.1845,
    phone: "+91 8181 254 112",
    history: "Nestled on a high rocky mountain top, this ancient cave sanctuary overlooks panoramic valley view reservoirs and dense forests.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Kundadri Digambar Jain Kshetra Committee",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-pavagadh",
    temple_name: "Pavagadh Hill Temples",
    temple_type: "Both",
    state: "Gujarat",
    city: "Pavagadh",
    address: "Pavagadh Hill Peak, Panchmahal District, Gujarat 389330",
    latitude: 22.4542,
    longitude: 73.5125,
    phone: "+91 2676 235 224",
    history: "Ancient spired stone temples dating back to the 11th century, dotting the steep volcanic peaks of Pavagadh Hill.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Chandraprabhu (8th Tirthankara)",
    trust_name: "Pavagadh Digambar-Shwetambar Joint Temple Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-karkala",
    temple_name: "Karkala Monolithic Monolith",
    temple_type: "Digambar",
    state: "Karnataka",
    city: "Karkala",
    address: "Bahubali Hill, Karkala, Udupi District, Karnataka 574104",
    latitude: 13.2125,
    longitude: 74.9812,
    phone: "+91 8258 233 112",
    history: "Features a majestic 42-foot monolithic granite statue of Gommateshwara, erected in 1432 AD on a rocky hill ridge.",
    timings: "6:00 AM - 7:30 PM",
    moolnayak: "Lord Bahubali (42-foot Monolith)",
    trust_name: "Karkala Digambar Jain Atishaya Kshetra Samiti",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-venur",
    temple_name: "Venur Bahubali Monolith",
    temple_type: "Digambar",
    state: "Karnataka",
    city: "Venur",
    address: "Venur Town Hill, Dakshina Kannada, Karnataka 574242",
    latitude: 13.0125,
    longitude: 75.1212,
    phone: "+91 8256 284 102",
    history: "A beautiful 35-foot monolithic statue of Lord Bahubali built in 1604 AD on the scenic bank of the Gurupura River.",
    timings: "6:00 AM - 7:00 PM",
    moolnayak: "Lord Bahubali (35-foot Monolith)",
    trust_name: "Venur Digambar Jain Basadi Committee",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-deogarh",
    temple_name: "Deogarh Fortress Temples",
    temple_type: "Digambar",
    state: "Uttar Pradesh",
    city: "Deogarh",
    address: "Deogarh Fort Hill, Lalitpur District, Uttar Pradesh 284403",
    latitude: 24.5212,
    longitude: 78.2512,
    phone: "+91 5176 283 234",
    history: "A massive complex of 31 ancient sandstone spired temples nestled inside the protective stone walls of Deogarh Fort.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Shantinath (16th Tirthankara)",
    trust_name: "Deogarh Digambar Jain Atishaya Kshetra Samiti",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-bhelupur",
    temple_name: "Varanasi Bhelupur Birthplace",
    temple_type: "Both",
    state: "Uttar Pradesh",
    city: "Varanasi",
    address: "Bhelupur Crossing, Varanasi, Uttar Pradesh 221010",
    latitude: 25.3045,
    longitude: 82.9812,
    phone: "+91 542 227 5214",
    history: "The highly revered, ancient birthplace of Lord Parshwanath, featuring serene white marble shrines near the Ganga River.",
    timings: "5:00 AM - 9:30 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Varanasi Digambar-Shwetambar Joint Birthplace Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-champapuri",
    temple_name: "Champapuri Vasupujya Tirth",
    temple_type: "Both",
    state: "Bihar",
    city: "Bhagalpur",
    address: "Champapuri Road, Bhagalpur, Bihar 812001",
    latitude: 25.2412,
    longitude: 86.9125,
    phone: "+91 641 242 5110",
    history: "The sacred birthplace and Nirvana destination of Lord Vasupujya, the 12th Tirthankara, housing massive spires.",
    timings: "5:30 AM - 8:30 PM",
    moolnayak: "Lord Vasupujya (12th Tirthankara)",
    trust_name: "Shree Champapuri Digambar-Shwetambar Jain Tirth Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-ayodhya",
    temple_name: "Ayodhya Tirth complex",
    temple_type: "Both",
    state: "Uttar Pradesh",
    city: "Ayodhya",
    address: "Jain Mandir Gali, Ayodhya, Uttar Pradesh 224123",
    latitude: 26.7912,
    longitude: 82.2012,
    phone: "+91 5278 222 110",
    history: "Birthplace of 5 Tirthankaras (including Lord Adinath), featuring a serene spired temple complex recently renovated.",
    timings: "5:30 AM - 9:00 PM",
    moolnayak: "Lord Adinath (1st Tirthankara)",
    trust_name: "Ayodhya Digambar-Shwetambar Jain Mandir Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-guniaji",
    temple_name: "Guniaji Jal Mandir",
    temple_type: "Both",
    state: "Bihar",
    city: "Nawada",
    address: "Guniaji Village Lake, Nawada District, Bihar 805110",
    latitude: 24.8912,
    longitude: 85.5812,
    phone: "+91 6112 284 102",
    history: "A scenic white temple in the center of a lotus tank, dedicated to Gautam Gandhar, the chief disciple of Lord Mahavira.",
    timings: "6:00 AM - 7:30 PM",
    moolnayak: "Lord Gautam Gandhar (Charan Paduka)",
    trust_name: "Shree Guniaji Jal Mandir Committee",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-lachhuar",
    temple_name: "Lachhuar Kshatriyakund Tirth",
    temple_type: "Shwetambar",
    state: "Bihar",
    city: "Jamui",
    address: "Kshatriyakund Hill, Jamui District, Bihar 811307",
    latitude: 24.9125,
    longitude: 86.2012,
    phone: "+91 6345 284 122",
    history: "Revered as the birthplace of Tirthankara Mahavira, situated in a serene green valley surrounded by scenic hills.",
    timings: "5:00 AM - 7:30 PM",
    moolnayak: "Lord Mahavira (24th Tirthankara)",
    trust_name: "Shree Lachhuar Shwetambar Jain Tirth Trust",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-shravasti",
    temple_name: "Shravasti Jain Shrine",
    temple_type: "Both",
    state: "Uttar Pradesh",
    city: "Shravasti",
    address: "Ahichhatra Road, Shravasti District, UP 271801",
    latitude: 27.5125,
    longitude: 82.0456,
    phone: "+91 5252 284 112",
    history: "Birthplace of the 3rd Tirthankara, Lord Sambhavnath, featuring beautiful marble carvings and spacious garden lawns.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Sambhavnath (3rd Tirthankara)",
    trust_name: "Shree Shravasti Jain Teerth Prabandhak Committee",
    image_url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-girnar",
    temple_name: "Girnar Shatrunjaya Maha-Tirth",
    temple_type: "Both",
    state: "Gujarat",
    city: "Junagadh",
    address: "Girnar Taleti, Junagadh District, Gujarat 362001",
    latitude: 21.5298,
    longitude: 70.4700,
    phone: "+91 285 262 1334",
    history: "An ancient, highly holy mountain-top tirth. The 5th peak houses the beautiful black stone temple of Lord Neminath (22nd Tirthankara), who attained renunciation, Kevalgyan, and Nirvana on this historic hill peak.",
    timings: "5:00 AM - 6:00 PM",
    moolnayak: "Lord Neminath (22nd Tirthankara)",
    trust_name: "Shree Bandhaji & Girnar Digambar-Shwetambar Joint Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Jain_temples_on_Mount_Girnar%2C_Junagadh.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-taranga",
    temple_name: "Taranga Hill Ajitnath Temple",
    temple_type: "Both",
    state: "Gujarat",
    city: "Mehsana",
    address: "Taranga Hill, Mehsana District, Gujarat 384350",
    latitude: 23.9789,
    longitude: 72.7689,
    phone: "+91 2761 283 124",
    history: "A landmark 12th-century spired stone temple built by the Solanki King Kumarpal in 1161 AD. The colossal structure is built of yellow sandstone and houses a serene 9-foot marble idol of Lord Ajitnath.",
    timings: "6:00 AM - 6:00 PM",
    moolnayak: "Lord Ajitnath (2nd Tirthankara)",
    trust_name: "Shree Taranga Jain Teerth Mahasabha",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/8/87/Taranga_Jain_temple.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-gajpanth",
    temple_name: "Gajpanth Siddha Kshetra",
    temple_type: "Digambar",
    state: "Maharashtra",
    city: "Nashik",
    address: "Gajpanth Hill, Mhasrul, Nashik District, Maharashtra 422004",
    latitude: 19.9975,
    longitude: 73.8242,
    phone: "+91 253 230 3574",
    history: "A highly revered Siddha Kshetra situated on a rocky hill ridge near Nashik. This is the holy site where 7 Balmukut (monks) achieved salvation, featuring beautiful rock-cut shrines and ancient footprints.",
    timings: "6:00 AM - 8:00 PM",
    moolnayak: "Lord Parshwanath (23rd Tirthankara)",
    trust_name: "Shree Gajpanth Digambar Jain Siddha Kshetra Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Shri_Digambar_Jain_Lal_Mandir%2C_Delhi.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-tijara",
    temple_name: "Tijara Chandraprabhu Atishaya Kshetra",
    temple_type: "Digambar",
    state: "Rajasthan",
    city: "Alwar",
    address: "Tijara Town, Alwar District, Rajasthan 301411",
    latitude: 27.9333,
    longitude: 76.8500,
    phone: "+91 1493 222 113",
    history: "A globally famous Atishaya Kshetra. In 1956 AD, a miraculous white-sand idol of Lord Chandraprabhu was discovered buried deep underground during structural excavations, prompting the creation of this massive modern temple complex.",
    timings: "5:00 AM - 10:00 PM",
    moolnayak: "Lord Chandraprabhu (8th Tirthankara)",
    trust_name: "Shree Digambar Jain Atishaya Kshetra Tijara Prabandh Samiti",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Shri_Digambar_Jain_Lal_Mandir%2C_Delhi.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: true,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-hastinapur",
    temple_name: "Hastinapur Shantinath Birthplace",
    temple_type: "Both",
    state: "Uttar Pradesh",
    city: "Meerut",
    address: "Hastinapur Town, Meerut District, Uttar Pradesh 250404",
    latitude: 29.1712,
    longitude: 78.0125,
    phone: "+91 1233 280 124",
    history: "The highly revered, ancient birthplace of three Tirthankaras: Lord Shantinath, Lord Kunthunath, and Lord Arahnath. Features massive circular structural models of Sumeru Parvat and the scenic jambudweep model.",
    timings: "5:00 AM - 9:30 PM",
    moolnayak: "Lord Shantinath (16th Tirthankara)",
    trust_name: "Hastinapur Joint Digambar-Shwetambar Tirth Committee",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Shri_Digambar_Jain_Lal_Mandir%2C_Delhi.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-rajgir",
    temple_name: "Rajgir Vaibhavgiri Hill Shrines",
    temple_type: "Both",
    state: "Bihar",
    city: "Nalanda",
    address: "Vaibhavgiri Hill Peak, Rajgir, Nalanda District, Bihar 803116",
    latitude: 25.0125,
    longitude: 85.4212,
    phone: "+91 6112 255 124",
    history: "Revered volcanic mountain ridges visited frequently by Lord Mahavira and Lord Buddha. The Vaibhavgiri peak houses five ancient spired stone temples and serene rocky hermitages overlooking natural hot springs.",
    timings: "6:00 AM - 5:30 PM",
    moolnayak: "Lord Munisuvratnath (20th Tirthankara)",
    trust_name: "Shree Rajgir Digambar-Shwetambar Joint Tirth Committee",
    image_url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: false,
      drinking_water_available: true,
      online_contact_available: false,
    }
  },
  {
    id: "t-ahinsasthal",
    temple_name: "Ahinsa Sthal (Mehrauli)",
    temple_type: "Both",
    state: "Delhi",
    city: "New Delhi",
    address: "Mehrauli Hillock, Near Qutub Minar, New Delhi 110030",
    latitude: 28.5256,
    longitude: 77.1845,
    phone: "+91 11 2664 1254",
    history: "A highly celebrated modern spiritual sanctuary situated on a pine hillock. It is famous for its majestic 13-foot monolithic granite statue of Lord Mahavira, overlooking the historical Qutub Minar landscape.",
    timings: "6:00 AM - 8:30 PM",
    moolnayak: "Lord Mahavira (13-foot Monolithic Statue)",
    trust_name: "Ahinsa Sthal Prabandhak Samiti New Delhi",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Shri_Digambar_Jain_Lal_Mandir%2C_Delhi.jpg",
    facilities: {
      dharamshala_available: false,
      bhojanshala_available: false,
      parking_available: true,
      ac_rooms_available: false,
      family_rooms_available: false,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: true,
    }
  },
  {
    id: "t-moodabidri",
    temple_name: "Moodabidri Saavira Kambada Basadi",
    temple_type: "Digambar",
    state: "Karnataka",
    city: "Moodabidri",
    address: "Basadi Marg, Moodabidri, Dakshina Kannada, Karnataka 574227",
    latitude: 13.0725,
    longitude: 74.9912,
    phone: "+91 8258 236 224",
    history: "Widely celebrated as the 'Jain Kashi' of South India. Built in 1430 AD, this monumental spired stone structure is supported by exactly 1,000 uniquely hand-carved pillars, with no two pillars sharing the same design.",
    timings: "6:00 AM - 7:30 PM",
    moolnayak: "Lord Chandranatha (8th Tirthankara)",
    trust_name: "Shree Moodabidri Digambar Jain Basadi Trust",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4e/1000_Pillar_Jain_Temple_Moodabidri.jpg",
    facilities: {
      dharamshala_available: true,
      bhojanshala_available: true,
      parking_available: true,
      ac_rooms_available: true,
      family_rooms_available: true,
      lift_available: false,
      wheelchair_accessible: true,
      drinking_water_available: true,
      online_contact_available: false,
    }
  }
];
